# Generated by Django 5.0.7 on 2024-08-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_document_user_document_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pickup', models.CharField(max_length=500)),
                ('dropoff', models.CharField(max_length=500)),
                ('paymentMethod', models.CharField(max_length=10)),
                ('dateTime', models.CharField(max_length=250)),
                ('distance', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
    ]
