# Generated by Django 5.0.7 on 2024-09-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_document_profilephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='profilePhoto',
        ),
    ]
