# Generated by Django 5.0.7 on 2024-09-18 11:08

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_document_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='profilePhoto',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
    ]
