# Generated by Django 5.0.7 on 2024-09-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='documentStatus',
            field=models.BooleanField(default=False),
        ),
    ]
