# Generated by Django 5.0.7 on 2024-09-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_driveravailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveravailability',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
