# Generated by Django 5.0.7 on 2024-09-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_mytrips_driver_alter_mytrips_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytrips',
            name='driver',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mytrips',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
