const airports = [
    { name: 'Bhopal Airport', code: 'BHO' },
    { name: 'Biju Patnaik International Airport', code: 'BBI' },
    { name: 'Birsa Munda Airport', code: 'IXR' },
    { name: 'Chaudhary Charan Singh International Airport', code: 'LKO' },
    { name: 'Chhatrapati Shivaji International Airport', code: 'BOM' },
    { name: 'Coimbatore International Airport', code: 'CJB' },
    { name: 'Dr. Babasaheb Ambedkar International Airport', code: 'NAG' },
    { name: 'Chennai International Airport', code: 'MAA' },
    { name: 'Cochin International Airport', code: 'COK' },
    { name: 'Devi Ahilya Bai Holkar Airport', code: 'IDR' },
    { name: 'Indira Gandhi International Airport', code: 'DEL' },
    { name: 'Jaipur International Airport', code: 'JAI' },
    { name: 'Jay Prakash Narayan International Airport', code: 'PAT' },
    { name: 'Jodhpur Airport', code: 'JDH' },
    { name: 'Kempegowda International Airport Bengaluru', code: 'BLR' },
    { name: 'Lokpriya Gopinath Bordoloi International Airport', code: 'GAU' },
    { name: 'Mangalore International Airport', code: 'IXE' },
    { name: 'Mysore Airport', code: 'MYQ' },
    { name: 'Netaji Subhas Chandra Bose International Airport', code: 'CCU' },
    { name: 'Pune International Airport', code: 'PNQ' },
    { name: 'Rajiv Gandhi International Airport', code: 'HYD' },
    { name: 'Sardar Vallabhbhai Patel International Airport', code: 'AMD' },
    { name: 'Surat Airport', code: 'STV' },
    { name: 'Trivandrum International Airport', code: 'TRV' },
    { name: 'Udaipur Airport', code: 'UDR' },
    { name: 'Vadodara Airport', code: 'BDQ' },
    { name: 'Vijayawada International Airport', code: 'VGA' },
    { name: 'Visakhapatnam Airport', code: 'VTZ' },
];
export default airports;